### ISSUE TITLE
Missing script: build:styles 

### ISSUE THREAD

**Issue by allengb208** [developers-sky/technojam-x#9]
### I am encountering an issue during the Docker build process with the following error message: **"Missing script: 'build:styles'**

The error reads :

> 
> 0.846 npm ERR! Missing script: "build:styles"
> 0.846 npm ERR!

How to Fix? 

Adding necessary dependencies to build styles using **Saas** inside package.json file .

**Comment by allengb208** [comment]
> hey @allengb208 would really, insist you make a PR. so that i can review changes or the issue. reply to this message with a code block that has error logs.

Already Solved , kindly check the pr.

**Comment by anurag-bit** [comment]
merged and tested check #10
